import dynamic from 'next/dynamic';
import { Button, Card, SectionHeading } from '@/components/ui';

const ThreeHeroScene = dynamic(() => import('@/components/ThreeHeroScene'), { ssr: false });

const pillars = [
['Authentic Korean Products','We focus on trusted Korean skincare brands and verified sourcing so customers can shop with confidence.'],
['Ingredient-Screened Selection','We review product ingredients for acne risk, irritation triggers, alcohol, fragrance, comedogenic concerns, and skin-type fit.'],
['Halal-Aware Curation','We clearly communicate available halal, vegan, cruelty-free, and animal-derived ingredient information wherever data is available.'],
['Selected for Pakistani Skin Needs','Our curation focuses on oily skin, acne marks, pigmentation, sensitive skin, sun exposure, humidity, heat, and sunscreen comfort.'],
['Fair and Competitive Pricing','Safe skincare should be accessible. We aim to bring trusted Korean skincare to Pakistan at fair and competitive prices.']
];

export default function Home() {
  return <main>
    <header className='sticky top-0 z-50 border-b border-forest/10 bg-cream/90 backdrop-blur'><nav className='container-x section flex h-20 items-center justify-between'><span className='font-serif text-2xl'>A Zero Circle</span><div className='hidden gap-8 text-sm md:flex'>{['Home','About','Ingredient Index','Partners','Contact'].map(x=><a key={x} href={`#${x.toLowerCase().replace(/ /g,'-')}`}>{x}</a>)}</div><Button href='#partners'>Partner With Us</Button></nav></header>
    <section id='home' className='section bg-mint py-20 md:py-28'><div className='container-x grid items-center gap-10 lg:grid-cols-2'><div><h1 className='font-serif text-5xl leading-tight md:text-7xl'>Safe Korean Skincare, Selected for Pakistan</h1><p className='mt-6 text-lg text-muted'>Authentic Korean skincare products from trusted and established brands, carefully screened for ingredients, halal-conscious concerns, skin suitability, and everyday Pakistani skincare needs.</p><p className='mt-6 text-sm text-forest'>Authentic sourcing • Ingredient-screened • Halal-aware • Women-led</p><div className='mt-8 flex flex-wrap gap-4'><Button>Explore Our Curation</Button><Button secondary href='#partners'>Partner With Us</Button></div></div><ThreeHeroScene /></div></section>
    <section className='section py-20'><div className='container-x'><SectionHeading id='about' title='K-beauty is loved in Pakistan. But buying it safely is still confusing.' desc='Many customers worry about fake products, unclear ingredients, high prices, sensitive skin reactions, animal-derived ingredients, and whether a product actually suits Pakistani skin, weather, and lifestyle.'/><SectionHeading id='solution' title='We make Korean skincare easier to trust.' desc='Before recommending a product, we look at authenticity, ingredient lists, acne and irritation risks, halal-conscious concerns, skin-type suitability, and value for money.'/></div></section>
    <section className='section bg-white py-20'><div className='container-x'><SectionHeading id='pillars' title='Why A Zero Circle?' /><div className='grid gap-5 md:grid-cols-2 lg:grid-cols-3'>{pillars.map((p,i)=><Card key={p[0]} title={p[0]} body={p[1]} delay={i*0.05} />)}</div></div></section>
    <section className='section bg-cream py-20'><div className='container-x'><SectionHeading id='curation' title='Korean skincare for real Pakistani routines' /><div className='grid gap-4 md:grid-cols-2 lg:grid-cols-5'>{['Sunscreens','Acne & Pore Care','Brightening & Pigmentation','Barrier Repair','Hydration & Glow'].map(x=><div className='rounded-2xl border border-forest/10 bg-white p-5' key={x}>{x}</div>)}</div></div></section>
    <section className='section bg-forest py-20 text-center text-white'><div className='container-x'><p className='mx-auto max-w-4xl font-serif text-3xl md:text-5xl'>“Our mission is to make Korean skincare in Pakistan easier to trust, easier to understand, and easier to choose.”</p><p className='mt-4 text-mint'>Founder, A Zero Circle</p></div></section>
    <section className='section py-20'><div className='container-x grid gap-8 lg:grid-cols-2'><article><SectionHeading id='brand-story' title='Built by a mom. Built for more women to rise.' desc='A Zero Circle is a women-led skincare business started by a stay-at-home mom to bring safer Korean skincare choices to Pakistan while creating opportunities for other women.'/></article><div className='rounded-3xl bg-pale p-8 text-muted'>Placeholder for <code>/public/images/women-led-founder.jpg</code></div></div></section>
    <section className='section bg-mint py-20'><div className='container-x'><SectionHeading id='tm-co' title='Backed by T&M Co.' desc='A Zero Circle is part of T&M Co., with nearly a decade of experience across retail, imports, technology, and product services.'/></div></section>
    <section id='partners' className='section py-20'><div className='container-x'><SectionHeading title='A trusted Pakistan launch partner for Korean skincare brands' id='partners-heading' desc='We help partner brands present themselves through authentic sourcing, inclusive messaging, ingredient transparency, halal-conscious product communication, and customer education.'/><Button>Partner With A Zero Circle</Button></div></section>
    <section id='ingredient-index' className='section bg-white py-20'><div className='container-x rounded-3xl border border-forest/10 bg-gradient-to-br from-mint to-cream p-10'><h2 className='font-serif text-4xl'>Coming Soon: A Zero Circle Ingredient Index</h2><p className='mt-4 max-w-3xl text-muted'>A searchable skincare ingredient database for Pakistan with ingredient analysis, acne and irritation flags, ingredient concern comparison, and halal-conscious notes.</p></div></section>
    <section className='section py-20'><div className='container-x text-center'><h2 className='font-serif text-4xl md:text-5xl'>Korean skincare should feel safe, clear, and trustworthy.</h2><p className='mx-auto mt-4 max-w-3xl text-muted'>A Zero Circle is building a better way to discover Korean skincare in Pakistan — with authentic sourcing, ingredient transparency, halal-aware curation, and a women-led purpose.</p><div className='mt-8 flex justify-center gap-4'><Button>Explore Our Curation</Button><Button secondary href='#partners'>Partner With Us</Button></div></div></section>
    <footer id='contact' className='section bg-forest py-12 text-mint'><div className='container-x'><p className='font-serif text-2xl text-white'>A Zero Circle</p><p className='mt-3 max-w-3xl text-sm'>A Zero Circle is a women-led Korean skincare platform in Pakistan, focused on authentic products, ingredient-screened curation, halal-conscious product awareness, and safer skincare education.</p><div className='mt-6 flex flex-wrap gap-4 text-sm'>{['Privacy Policy','Terms','About','Ingredient Index','Partner With Us','Contact','Instagram','WhatsApp'].map(x=><a key={x} href='#'>{x}</a>)}</div><p className='mt-6 text-xs'>A Zero Circle is part of T&M Co. © A Zero Circle. All rights reserved.</p></div></footer>
  </main>;
}
